### ISSUE TITLE
在 Xcode build 代码失败

### ISSUE THREAD

**Issue by mcattx** [wolfhous/HSEther#1]
环境： 
- Xcode Version 8.3.3 (8E3004b)
- macOS (10.12.6)
---
操作如下：

1. git clone 代码
2. 打开 Xcode ，然后 `Command + O` 打开 `HSEther/HSEtherDemoHSEther.xcodeproj` ，发现 build 的时候出错

---
报错如下：
![image](https://user-images.githubusercontent.com/3294102/41961951-70e1710c-7a26-11e8-96bd-6cc98c7b3878.png)

**Comment by wolfhous** [comment]
建议你使用xcode 9以上工具打开。

**Comment by mcattx** [comment]
我试一下

**Comment by mcattx** [comment]
@wolfhous 更新 XCode 到 9 就没问题了。
